/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "LakeSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LakeUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PosthogToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "Server": cloudflare.Service
  }
}

import "sst"
export {}