# https://huggingface.co/CohereLabs/aya-expanse-32b
name = "Aya Expanse 32B"
description = "Open multilingual model optimized for generation across 23 languages"
release_date = "2024-10-24"
last_updated = "2024-10-24"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = true
license = "CC-BY-NC-4.0"

[limit]
context = 128_000
output = 4_000

[modalities]
input = ["text"]
output = ["text"]

[[weights]]
label = "Hugging Face"
url = "https://huggingface.co/CohereLabs/aya-expanse-32b"
